### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec

### ISSUE THREAD

**Issue by tech2h** [Slyyxp/OtotoyPy#2]
Hi Sly
Thank you for the script. I am getting an error while downloading downloading anything with any special character other than "." i.e. 554926 works but not 556482. And it happens to all any other character other than plain English. It happen if the special character in file name or folder name.

>  File "main.py", line 264, in <module>
    main()
  File "main.py", line 253, in main
    post = download_track(track=track, ap=ap)
  File "main.py", line 147, in download_track
    os.rename(pre, post)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 36: ordinal not in range(128)

I am using it on seedbox and I am using python3.5 I cant install requirements on python3.8 everytime I try using "pip install -r requirements.txt" it install required file to python3.5.

I have attached log file if that help.

I hope to all this make sense.

thank you 
[04_35_17.log](https://github.com/Slyyxp/OtotoyPy/files/4756218/04_35_17.log)
[04_33_56.log](https://github.com/Slyyxp/OtotoyPy/files/4756219/04_33_56.log)
[04_40_12.log](https://github.com/Slyyxp/OtotoyPy/files/4756220/04_40_12.log)
[04_37_28.log](https://github.com/Slyyxp/OtotoyPy/files/4756221/04_37_28.log)

**Comment by Slyyxp** [comment]
Issues should only be opened after finding a legitimate issue.
I have never advertised that this script supports versions below 3.8.0.

If you have trouble understanding your Python environment perhaps try asking for help in the Python discord.

But to give you a quick answer if requirements are not installing to 3.8.0 then you're not installing using the correct version of pip.
