### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by littlealone100** [Slyyxp/OtotoyPy#3]
not work with album code 54385
may because that album no cover?

AttributeError:'NoneType' object has no attribute 'replace'

screenshot
https://imgur.com/uDXHkru

PS: I already use lastest script.

**Comment by Slyyxp** [comment]
This issue has been resolved in the latest commit using an AttributeError Exception and an additional check on MP3's.
https://github.com/Slyyxp/OtotoyPy/commit/c1da0c75b348ea9144e786a0e9972c3c5d60108a
