### ISSUE TITLE
Downloads lossy instead of lossless (where lossless is available)

### ISSUE THREAD

**Issue by xdanguyx** [Slyyxp/OtotoyPy#5]
I've tried to grab a handful from this label which offers lossless options for everything listed but each time I queue an album it downloads mp3 instead.  I have my doubts that it's an issue with the script bc it works for most everything else I've used it for but as I've mentioned the entire page is supposed to be available in lossless and for some odd reason is only grabbed in mp3 form.  Hopefully you are able to get it sorted or can provide some insight as to what's happening.  Thanks for your time!

https://ototoy.jp/labels/77381

**Comment by Slyyxp** [comment]
You are correct in saying this is not an error with this script.
If you check your logs you will notice that the API returns "permitted_format".
The only format returned for these specific albums is MP3.

There could be 2 reasons for this..
1: It's an error in their system.
2: The mobile application this API is used for does not permit flac streaming/purchases on these particular albums.

However, you can force FLAC manually even for albums that seem to not have FLAC available for purchase on their store.

I have refactored the format_decision() function in the latest commit https://github.com/Slyyxp/OtotoyPy/commit/3272a260cffc8130daf6f4fc411f22ba2784393d to support the forcing of FLAC when specified using the -f command.

Example usage:
`python main.py -u "https://ototoy.jp/_/default/p/36666" -f "flac"`

**Comment by xdanguyx** [comment]
Works flawlessly now thanks!  Will review log in the future for issues.  Thanks!
